-- Insercao dos Usuarios
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('Administrador','123.456.789-10', 'admin@sgcmf.com', 'Administrador','admin','admin');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('Comite Gestor 1','785.456.781-90', 'usuario18@sgcmf.com', 'Membro Comite','comite','comite');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('Entusiasta 1','785.456.781-20', 'usuario20@sgcmf.com', 'Entusiasta','entusiasta','entusiasta');

insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tFranca','321.456.789-30', 'usuario3@sgcmf.com', 'Tecnico da Selecao','tFranca','tFranca');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tMexico','423.156.789-40', 'usuario4@sgcmf.com', 'Tecnico da Selecao','tMexico','tMexico');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tAfricaSul','523.416.789-50', 'usuario5@sgcmf.com', 'Tecnico da Selecao','tAfricaSul','tAfricaSul');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tUruguai','623.451.789-60', 'usuario6@sgcmf.com', 'Tecnico da Selecao','tUruguai','tUruguai');

insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tArgentina','723.456.189-70', 'usuario7@sgcmf.com', 'Tecnico da Selecao','tArgentina','tArgentina');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tGrecia','823.456.189-80', 'usuario8@sgcmf.com', 'Tecnico da Selecao','tGrecia','tGrecia');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tNigeria','923.456.781-90', 'usuario9@sgcmf.com', 'Tecnico da Selecao','tNigeria','tNigeria');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tCoreiaDoSul','231.456.789.10', 'usuario10@sgcmf.com', 'Tecnico da Selecao','tCoreiaDoSul','tCoreiaDoSul');

insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tAlgeria','132.456.789-20', 'usuario11@sgcmf.com', 'Tecnico da Selecao','tAlgeria','tAlgeria');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tInglaterra','134.256.789-30', 'usuario12@sgcmf.com', 'Tecnico da Selecao','tInglaterra','tInglaterra');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tEslovenia','671.416.789-40', 'usuario13@sgcmf.com', 'Tecnico da Selecao','tEslovenia','tEslovenia');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tEstadosUnidos','387.451.789-50', 'usuario14@sgcmf.com', 'Tecnico da Selecao','tEstadosUnidos','tEstadosUnidos');

insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tAustralia','413.456.189-60', 'usuario15@sgcmf.com', 'Tecnico da Selecao','tAustralia','tAustralia');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tAlemanha','911.456.189-70', 'usuario16@sgcmf.com', 'Tecnico da Selecao','tAlemanha','tAlemanha');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tGana','785.456.781-80', 'usuario17@sgcmf.com', 'Tecnico da Selecao','tGana','tGana');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tServia','785.456.781-81', 'usuario21@sgcmf.com', 'Tecnico da Selecao','tServia','tServia');

insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tCamaroes','785.456.781-82', 'usuario22@sgcmf.com', 'Tecnico da Selecao','tCamaroes','tCamaroes');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tDinamarca','785.456.781-83', 'usuario23@sgcmf.com', 'Tecnico da Selecao','tDinamarca','tDinamarca');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tJapao','785.456.781-84', 'usuario24@sgcmf.com', 'Tecnico da Selecao','tJapao','tJapao');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tHolanda','785.456.781-85', 'usuario25@sgcmf.com', 'Tecnico da Selecao','tHolanda','tHolanda');

insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tItalia','785.456.781-86', 'usuario26@sgcmf.com', 'Tecnico da Selecao','tItalia','tItalia');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tNovaZelandia','785.456.781-87', 'usuario27@sgcmf.com', 'Tecnico da Selecao','tNovaZelandia','tNovaZelandia');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tParaguai','785.456.781-88', 'usuario28@sgcmf.com', 'Tecnico da Selecao','tParaguai','tParaguai');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tEslovaquia','785.456.781-89', 'usuario29@sgcmf.com', 'Tecnico da Selecao','tEslovaquia','tEslovaquia');

insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tBrasil','785.456.782-90', 'usuario30@sgcmf.com', 'Tecnico da Selecao','tBrasil','tBrasil');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tCostaDoMarfim','785.456.781-91', 'usuario31@sgcmf.com', 'Tecnico da Selecao','tCostaDoMarfim','tCostaDoMarfim');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tCoreiaDoNorte','785.456.781-92', 'usuario32@sgcmf.com', 'Tecnico da Selecao','tCoreiaDoNorte','tCoreiaDoNorte');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tPortugal','785.456.781-93', 'usuario33@sgcmf.com', 'Tecnico da Selecao','tPortugal','tPortugal');

insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tChile','785.456.781-94', 'usuario34@sgcmf.com', 'Tecnico da Selecao','tChile','tChile');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tEquador','785.456.781-95', 'usuario35@sgcmf.com', 'Tecnico da Selecao','tEquador','tEquador');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tHonduras','785.456.781-96', 'usuario36@sgcmf.com', 'Tecnico da Selecao','tHonduras','tHonduras');
insert into Usuario (nome, cpf, email, perfil, login, senha) values ('tEspanha','785.456.781-97', 'usuario37@sgcmf.com', 'Tecnico da Selecao','tEspanha','tEspanha');

-- Insercao das Selecoes
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Franca','img/selecoes32/grupoa/France.png',4, 'A');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Mexico','img/selecoes32/grupoa/Mexico.png',5, 'A');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Africa do Sul','img/selecoes32/grupoa/South-Africa.png',6, 'A');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Uruguai','img/selecoes32/grupoa/Uruguay.png',7, 'A');

insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Argentina','img/selecoes32/grupob/Argentina.png',8, 'B');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Grecia','img/selecoes32/grupob/Greece.png',9, 'B');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Nigeria','img/selecoes32/grupob/Nigeria.png',10, 'B');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Coreia do sul','img/selecoes32/grupob/South-Korea.png',11, 'B');

insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Algeria','img/selecoes32/grupoc/Algeria.png',12, 'C');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Inglaterra','img/selecoes32/grupoc/England.png',13, 'C');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Eslovenia','img/selecoes32/grupoc/Slovenia.png',14, 'C');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Estados Unidos','img/selecoes32/grupoc/United-States.png',15, 'C');

insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Australia','img/selecoes32/grupod/Australia.png',16, 'D');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Alemanha','img/selecoes32/grupod/Germany.png',17, 'D');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Gana','img/selecoes32/grupod/Ghana.png',18, 'D');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Servia','img/selecoes32/grupod/Serbia.png',19, 'D');

insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Camaroes','img/selecoes32/grupoe/Cameroon.png',20, 'E');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Dinamarca','img/selecoes32/grupoe/Denmark.png',21, 'E');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Japao','img/selecoes32/grupoe/Japan.png',22, 'E');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Holanda','img/selecoes32/grupoe/Netherlands.png',23, 'E');

insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Italia','img/selecoes32/grupof/Italy.png',24, 'F');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Nova Zelandia','img/selecoes32/grupof/New-Zealand.png',25, 'F');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Paraguai','img/selecoes32/grupof/Paraguay.png',26, 'F');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Eslovaquia','img/selecoes32/grupof/Slovakia.png',27, 'F');

insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Brasil','img/selecoes32/grupog/Brazil.png',28, 'G');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Costa do Marfim','img/selecoes32/grupog/Cote-dIvoire.png',29, 'G');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Coreia do Norte','img/selecoes32/grupog/North-Korea.png',30, 'G');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Portugal','img/selecoes32/grupog/Portugal.png',31, 'G');

insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Chile','img/selecoes32/grupoh/Chile.png',32, 'H');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Equador', 'img/selecoes32/grupoh/Ecuador.png',33, 'H');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo) values ('Honduras','img/selecoes32/grupoh/Honduras.png',34, 'H');
insert into Selecao (pais, caminhoImgBandeira, idUsuarioTecnico, grupo)  values ('Espanha','img/selecoes32/grupoh/Spain.png',35, 'H');

-- Insercao dos Jogos
--grupo a
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 1,2,'2014-06-11 11:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 1,3,'2014-06-12 11:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 1,4,'2014-06-13 11:20:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 2,3,'2014-06-14 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 2,4,'2014-06-15 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 3,4,'2014-06-16 12:00:00 -03');

--grupob
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 5,6,'2014-06-11 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 5,7,'2014-06-12 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 5,8,'2014-06-13 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 6,7,'2014-06-14 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 6,8,'2014-06-15 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 7,8,'2014-06-16 12:00:00 -03');

--grupo c
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 9,10,'2014-06-11 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 9,11,'2014-06-12 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 9,12,'2014-06-13 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 10,11,'2014-06-14 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 10,12,'2014-06-15 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 11,12,'2014-06-16 12:00:00 -03');

--grupo d
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 13,14,'2014-06-11 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 13,15,'2014-06-12 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 13,16,'2014-06-13 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 14,15,'2014-06-14 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 14,16,'2014-06-15 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 15,16,'2014-06-16 12:00:00 -03');

--grupo e
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 17,18,'2014-06-11 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 17,19,'2014-06-12 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 17,20,'2014-06-13 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 18,19,'2014-06-14 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 18,20,'2014-06-15 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 19,20,'2014-06-16 12:00:00 -03');

--grupo f
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 21,22,'2014-06-11 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 21,23,'2014-06-12 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 21,24,'2014-06-13 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 22,23,'2014-06-14 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 22,24,'2014-06-15 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 23,24,'2014-06-16 12:00:00 -03');

--grupo g
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 25,26,'2014-06-11 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 25,27,'2014-06-12 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 25,28,'2014-06-13 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 26,27,'2014-06-14 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 26,28,'2014-06-15 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 27,28,'2014-06-16 12:00:00 -03');

--grupo h
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 29,30,'2014-06-11 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 29,31,'2014-06-12 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 29,32,'2014-06-13 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Rio de Janeiro', 'Maracana', 30,31,'2014-06-14 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Sao Paulo', 'Morumbi', 30,32,'2014-06-15 12:00:00 -03');
insert into Jogo (cidade, nomeEstadio, idSelecaoI, idSelecaoII, dataHora) values ('Belo Horizonte', 'Mineirao', 31,32,'2014-06-16 12:00:00 -03');

-- Insercao dos Jogadores
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 1', 1.52, 1, '1983-4-28', 'Goleiro', true, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 2', 1.65, 2, '1972-10-10', 'Zagueiro', true, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 3', 1.54, 3, '1969-3-3', 'Lateral Esquerdo', true, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 4', 1.70, 4, '1962-12-1', 'Lateral Esquerdo', true, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 5', 1.68, 5, '1976-8-15', 'Lateral Direito', true, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 6', 1.74, 6, '1976-2-23', 'Lateral Direito', true, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 7', 1.90, 7, '1971-10-9', 'Volante', true, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 8', 1.52, 8, '1960-4-1', 'Atacante', true, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 9', 1.91, 9, '1970-2-21', 'Goleiro', false, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 10', 1.76, 10, '1984-4-24', 'Goleiro', false, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 11', 1.68, 11, '1961-4-28', 'Zagueiro', false, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 12', 1.79, 12, '1975-3-24', 'Atacante', false, 1);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 13', 1.82, 1, '1961-9-21', 'Goleiro', true, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 14', 1.58, 2, '1961-1-23', 'Zagueiro', true, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 15', 1.59, 3, '1961-3-20', 'Lateral Esquerdo', true, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 16', 1.59, 4, '1985-9-3', 'Lateral Esquerdo', true, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 17', 1.79, 5, '1974-3-1', 'Lateral Direito', true, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 18', 1.75, 6, '1967-4-19', 'Lateral Direito', true, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 19', 1.83, 7, '1985-10-6', 'Volante', true, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 20', 1.99, 8, '1981-5-15', 'Atacante', true, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 21', 1.76, 9, '1983-3-28', 'Goleiro', false, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 22', 1.89, 10, '1976-12-3', 'Goleiro', false, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 23', 1.90, 11, '1984-11-10', 'Zagueiro', false, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 24', 1.93, 12, '1969-10-15', 'Atacante', false, 2);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 25', 1.57, 1, '1978-1-5', 'Goleiro', true, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 26', 1.92, 2, '1982-10-18', 'Zagueiro', true, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 27', 1.90, 3, '1966-7-14', 'Lateral Esquerdo', true, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 28', 1.74, 4, '1967-2-1', 'Lateral Esquerdo', true, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 29', 1.90, 5, '1988-9-26', 'Lateral Direito', true, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 30', 1.67, 6, '1983-3-28', 'Lateral Direito', true, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 31', 1.87, 7, '1984-8-18', 'Volante', true, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 32', 1.66, 8, '1978-12-2', 'Atacante', true, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 33', 1.91, 9, '1987-12-6', 'Goleiro', false, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 34', 1.99, 10, '1966-2-2', 'Goleiro', false, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 35', 1.65, 11, '1973-7-10', 'Zagueiro', false, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 36', 1.57, 12, '1973-12-1', 'Atacante', false, 3);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 37', 1.96, 1, '1964-8-7', 'Goleiro', true, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 38', 1.90, 2, '1976-10-18', 'Zagueiro', true, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 39', 1.72, 3, '1963-12-26', 'Lateral Esquerdo', true, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 40', 1.58, 4, '1960-4-9', 'Lateral Esquerdo', true, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 41', 1.98, 5, '1961-11-27', 'Lateral Direito', true, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 42', 1.82, 6, '1971-1-24', 'Lateral Direito', true, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 43', 1.52, 7, '1962-12-28', 'Volante', true, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 44', 1.51, 8, '1980-10-25', 'Atacante', true, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 45', 1.64, 9, '1981-4-24', 'Goleiro', false, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 46', 1.52, 10, '1965-10-17', 'Goleiro', false, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 47', 1.73, 11, '1968-7-28', 'Zagueiro', false, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 48', 1.58, 12, '1989-6-3', 'Atacante', false, 4);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 49', 1.52, 1, '1972-6-19', 'Goleiro', true, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 50', 1.72, 2, '1989-9-12', 'Zagueiro', true, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 51', 1.71, 3, '1961-10-17', 'Lateral Esquerdo', true, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 52', 1.97, 4, '1964-12-11', 'Lateral Esquerdo', true, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 53', 1.94, 5, '1979-9-9', 'Lateral Direito', true, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 54', 1.66, 6, '1962-12-14', 'Lateral Direito', true, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 55', 1.95, 7, '1980-7-21', 'Volante', true, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 56', 1.65, 8, '1976-3-26', 'Atacante', true, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 57', 1.89, 9, '1979-7-18', 'Goleiro', false, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 58', 1.72, 10, '1986-4-23', 'Goleiro', false, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 59', 1.94, 11, '1972-2-2', 'Zagueiro', false, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 60', 1.79, 12, '1976-9-11', 'Atacante', false, 5);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 61', 1.69, 1, '1972-10-28', 'Goleiro', true, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 62', 1.70, 2, '1971-1-24', 'Zagueiro', true, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 63', 1.74, 3, '1969-3-20', 'Lateral Esquerdo', true, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 64', 1.70, 4, '1974-12-15', 'Lateral Esquerdo', true, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 65', 1.68, 5, '1966-10-28', 'Lateral Direito', true, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 66', 1.64, 6, '1975-9-12', 'Lateral Direito', true, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 67', 1.89, 7, '1962-12-22', 'Volante', true, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 68', 1.50, 8, '1965-9-13', 'Atacante', true, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 69', 1.67, 9, '1977-6-9', 'Goleiro', false, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 70', 1.91, 10, '1981-6-14', 'Goleiro', false, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 71', 1.73, 11, '1962-8-1', 'Zagueiro', false, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 72', 1.56, 12, '1967-5-21', 'Atacante', false, 6);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 73', 1.55, 1, '1965-11-13', 'Goleiro', true, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 74', 1.94, 2, '1960-3-6', 'Zagueiro', true, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 75', 1.82, 3, '1967-3-21', 'Lateral Esquerdo', true, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 76', 1.71, 4, '1962-3-6', 'Lateral Esquerdo', true, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 77', 1.88, 5, '1987-11-11', 'Lateral Direito', true, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 78', 1.61, 6, '1976-7-2', 'Lateral Direito', true, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 79', 1.78, 7, '1971-2-16', 'Volante', true, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 80', 1.54, 8, '1989-7-28', 'Atacante', true, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 81', 1.74, 9, '1965-1-13', 'Goleiro', false, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 82', 1.58, 10, '1961-2-3', 'Goleiro', false, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 83', 1.52, 11, '1965-6-22', 'Zagueiro', false, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 84', 1.99, 12, '1984-10-17', 'Atacante', false, 7);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 85', 1.86, 1, '1980-9-12', 'Goleiro', true, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 86', 1.85, 2, '1976-7-9', 'Zagueiro', true, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 87', 1.61, 3, '1987-1-16', 'Lateral Esquerdo', true, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 88', 1.72, 4, '1968-12-17', 'Lateral Esquerdo', true, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 89', 1.65, 5, '1978-11-16', 'Lateral Direito', true, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 90', 1.67, 6, '1966-7-8', 'Lateral Direito', true, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 91', 1.57, 7, '1964-7-23', 'Volante', true, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 92', 1.53, 8, '1986-7-2', 'Atacante', true, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 93', 1.99, 9, '1978-1-16', 'Goleiro', false, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 94', 1.52, 10, '1969-5-5', 'Goleiro', false, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 95', 1.71, 11, '1985-4-7', 'Zagueiro', false, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 96', 1.72, 12, '1977-2-3', 'Atacante', false, 8);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 97', 1.66, 1, '1984-3-6', 'Goleiro', true, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 98', 1.90, 2, '1980-3-15', 'Zagueiro', true, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 99', 1.51, 3, '1975-10-28', 'Lateral Esquerdo', true, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 100', 1.68, 4, '1969-9-27', 'Lateral Esquerdo', true, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 101', 1.55, 5, '1982-11-22', 'Lateral Direito', true, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 102', 1.55, 6, '1978-7-8', 'Lateral Direito', true, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 103', 1.56, 7, '1962-7-1', 'Volante', true, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 104', 1.95, 8, '1962-1-14', 'Atacante', true, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 105', 1.71, 9, '1967-3-7', 'Goleiro', false, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 106', 1.93, 10, '1986-3-7', 'Goleiro', false, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 107', 1.61, 11, '1986-7-24', 'Zagueiro', false, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 108', 1.56, 12, '1986-7-8', 'Atacante', false, 9);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 109', 1.63, 1, '1980-3-13', 'Goleiro', true, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 110', 1.65, 2, '1976-10-5', 'Zagueiro', true, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 111', 1.89, 3, '1960-8-1', 'Lateral Esquerdo', true, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 112', 1.54, 4, '1962-3-18', 'Lateral Esquerdo', true, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 113', 1.85, 5, '1967-12-22', 'Lateral Direito', true, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 114', 1.62, 6, '1962-9-28', 'Lateral Direito', true, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 115', 1.58, 7, '1977-10-17', 'Volante', true, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 116', 1.91, 8, '1975-10-2', 'Atacante', true, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 117', 1.81, 9, '1979-6-18', 'Goleiro', false, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 118', 1.63, 10, '1978-2-5', 'Goleiro', false, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 119', 1.99, 11, '1968-12-2', 'Zagueiro', false, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 120', 1.68, 12, '1962-1-27', 'Atacante', false, 10);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 121', 1.83, 1, '1968-9-15', 'Goleiro', true, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 122', 1.58, 2, '1961-4-10', 'Zagueiro', true, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 123', 1.53, 3, '1974-8-7', 'Lateral Esquerdo', true, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 124', 1.96, 4, '1971-1-1', 'Lateral Esquerdo', true, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 125', 1.63, 5, '1961-12-2', 'Lateral Direito', true, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 126', 1.52, 6, '1977-10-7', 'Lateral Direito', true, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 127', 1.86, 7, '1972-6-14', 'Volante', true, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 128', 1.71, 8, '1978-9-9', 'Atacante', true, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 129', 1.67, 9, '1982-2-5', 'Goleiro', false, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 130', 1.87, 10, '1971-6-5', 'Goleiro', false, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 131', 1.90, 11, '1980-11-20', 'Zagueiro', false, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 132', 1.81, 12, '1961-4-5', 'Atacante', false, 11);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 133', 1.82, 1, '1980-4-14', 'Goleiro', true, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 134', 1.56, 2, '1963-3-17', 'Zagueiro', true, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 135', 1.67, 3, '1975-4-6', 'Lateral Esquerdo', true, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 136', 1.82, 4, '1989-5-22', 'Lateral Esquerdo', true, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 137', 1.58, 5, '1960-2-3', 'Lateral Direito', true, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 138', 2.00, 6, '1976-6-18', 'Lateral Direito', true, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 139', 1.81, 7, '1976-5-18', 'Volante', true, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 140', 1.51, 8, '1978-10-26', 'Atacante', true, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 141', 1.87, 9, '1978-6-28', 'Goleiro', false, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 142', 1.68, 10, '1974-6-16', 'Goleiro', false, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 143', 1.95, 11, '1970-2-21', 'Zagueiro', false, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 144', 1.60, 12, '1966-3-18', 'Atacante', false, 12);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 145', 1.81, 1, '1986-6-2', 'Goleiro', true, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 146', 1.76, 2, '1969-12-16', 'Zagueiro', true, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 147', 1.62, 3, '1978-4-14', 'Lateral Esquerdo', true, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 148', 1.52, 4, '1963-5-6', 'Lateral Esquerdo', true, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 149', 1.79, 5, '1968-2-13', 'Lateral Direito', true, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 150', 1.95, 6, '1962-1-28', 'Lateral Direito', true, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 151', 1.87, 7, '1961-4-13', 'Volante', true, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 152', 1.59, 8, '1970-4-5', 'Atacante', true, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 153', 1.89, 9, '1976-9-19', 'Goleiro', false, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 154', 1.92, 10, '1962-2-2', 'Goleiro', false, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 155', 1.58, 11, '1963-7-21', 'Zagueiro', false, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 156', 1.81, 12, '1973-8-6', 'Atacante', false, 13);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 157', 1.87, 1, '1969-12-14', 'Goleiro', true, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 158', 1.60, 2, '1976-11-6', 'Zagueiro', true, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 159', 1.72, 3, '1962-4-16', 'Lateral Esquerdo', true, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 160', 1.58, 4, '1963-11-13', 'Lateral Esquerdo', true, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 161', 1.86, 5, '1963-1-24', 'Lateral Direito', true, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 162', 1.65, 6, '1974-6-28', 'Lateral Direito', true, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 163', 1.94, 7, '1969-7-5', 'Volante', true, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 164', 1.91, 8, '1979-12-3', 'Atacante', true, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 165', 1.87, 9, '1987-9-15', 'Goleiro', false, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 166', 1.60, 10, '1970-5-18', 'Goleiro', false, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 167', 1.83, 11, '1961-7-18', 'Zagueiro', false, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 168', 1.86, 12, '1960-5-24', 'Atacante', false, 14);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 169', 1.76, 1, '1973-5-18', 'Goleiro', true, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 170', 1.84, 2, '1966-11-8', 'Zagueiro', true, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 171', 1.90, 3, '1982-4-10', 'Lateral Esquerdo', true, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 172', 1.76, 4, '1967-9-24', 'Lateral Esquerdo', true, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 173', 1.80, 5, '1963-9-15', 'Lateral Direito', true, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 174', 1.89, 6, '1984-9-3', 'Lateral Direito', true, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 175', 1.88, 7, '1978-10-6', 'Volante', true, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 176', 1.99, 8, '1988-6-11', 'Atacante', true, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 177', 1.59, 9, '1970-11-5', 'Goleiro', false, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 178', 1.90, 10, '1982-10-23', 'Goleiro', false, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 179', 1.81, 11, '1988-12-10', 'Zagueiro', false, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 180', 1.89, 12, '1969-7-16', 'Atacante', false, 15);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 181', 1.90, 1, '1963-7-9', 'Goleiro', true, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 182', 1.96, 2, '1988-12-8', 'Zagueiro', true, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 183', 1.75, 3, '1965-4-16', 'Lateral Esquerdo', true, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 184', 1.86, 4, '1965-4-23', 'Lateral Esquerdo', true, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 185', 1.78, 5, '1976-9-11', 'Lateral Direito', true, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 186', 1.89, 6, '1981-8-19', 'Lateral Direito', true, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 187', 1.64, 7, '1973-12-6', 'Volante', true, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 188', 1.98, 8, '1989-2-5', 'Atacante', true, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 189', 1.55, 9, '1964-12-13', 'Goleiro', false, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 190', 1.90, 10, '1969-1-2', 'Goleiro', false, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 191', 1.92, 11, '1981-6-7', 'Zagueiro', false, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 192', 1.71, 12, '1975-12-25', 'Atacante', false, 16);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 193', 1.93, 1, '1973-2-22', 'Goleiro', true, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 194', 1.53, 2, '1989-3-4', 'Zagueiro', true, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 195', 1.62, 3, '1969-5-25', 'Lateral Esquerdo', true, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 196', 2.00, 4, '1968-6-19', 'Lateral Esquerdo', true, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 197', 1.80, 5, '1971-8-26', 'Lateral Direito', true, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 198', 1.95, 6, '1961-8-23', 'Lateral Direito', true, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 199', 1.72, 7, '1962-6-26', 'Volante', true, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 200', 1.95, 8, '1965-12-14', 'Atacante', true, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 201', 1.95, 9, '1966-11-22', 'Goleiro', false, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 202', 1.96, 10, '1971-11-4', 'Goleiro', false, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 203', 1.78, 11, '1981-9-26', 'Zagueiro', false, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 204', 1.73, 12, '1988-1-13', 'Atacante', false, 17);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 205', 1.54, 1, '1974-5-7', 'Goleiro', true, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 206', 1.98, 2, '1989-3-23', 'Zagueiro', true, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 207', 1.74, 3, '1962-1-12', 'Lateral Esquerdo', true, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 208', 1.95, 4, '1973-3-13', 'Lateral Esquerdo', true, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 209', 1.58, 5, '1977-5-13', 'Lateral Direito', true, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 210', 1.73, 6, '1982-6-24', 'Lateral Direito', true, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 211', 1.63, 7, '1979-3-8', 'Volante', true, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 212', 1.82, 8, '1964-11-21', 'Atacante', true, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 213', 1.78, 9, '1963-1-13', 'Goleiro', false, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 214', 1.93, 10, '1987-12-4', 'Goleiro', false, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 215', 1.91, 11, '1977-5-15', 'Zagueiro', false, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 216', 1.84, 12, '1970-6-11', 'Atacante', false, 18);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 217', 1.90, 1, '1989-10-25', 'Goleiro', true, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 218', 1.58, 2, '1972-1-23', 'Zagueiro', true, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 219', 1.53, 3, '1979-2-21', 'Lateral Esquerdo', true, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 220', 1.51, 4, '1960-10-5', 'Lateral Esquerdo', true, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 221', 1.69, 5, '1988-6-23', 'Lateral Direito', true, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 222', 1.92, 6, '1986-2-21', 'Lateral Direito', true, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 223', 1.98, 7, '1960-8-13', 'Volante', true, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 224', 1.80, 8, '1975-1-10', 'Atacante', true, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 225', 1.59, 9, '1969-2-7', 'Goleiro', false, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 226', 1.79, 10, '1969-11-21', 'Goleiro', false, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 227', 1.94, 11, '1972-10-24', 'Zagueiro', false, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 228', 1.69, 12, '1980-12-22', 'Atacante', false, 19);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 229', 1.66, 1, '1982-10-17', 'Goleiro', true, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 230', 1.85, 2, '1968-12-18', 'Zagueiro', true, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 231', 1.99, 3, '1970-8-11', 'Lateral Esquerdo', true, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 232', 1.80, 4, '1967-10-15', 'Lateral Esquerdo', true, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 233', 1.62, 5, '1974-12-15', 'Lateral Direito', true, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 234', 1.78, 6, '1987-1-17', 'Lateral Direito', true, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 235', 1.51, 7, '1978-5-21', 'Volante', true, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 236', 1.71, 8, '1980-6-27', 'Atacante', true, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 237', 1.63, 9, '1961-4-2', 'Goleiro', false, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 238', 1.81, 10, '1976-4-23', 'Goleiro', false, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 239', 1.64, 11, '1976-1-4', 'Zagueiro', false, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 240', 1.63, 12, '1984-11-21', 'Atacante', false, 20);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 241', 1.79, 1, '1974-6-19', 'Goleiro', true, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 242', 1.51, 2, '1971-7-4', 'Zagueiro', true, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 243', 1.86, 3, '1969-1-22', 'Lateral Esquerdo', true, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 244', 1.80, 4, '1979-9-3', 'Lateral Esquerdo', true, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 245', 1.54, 5, '1987-12-7', 'Lateral Direito', true, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 246', 1.51, 6, '1968-10-13', 'Lateral Direito', true, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 247', 1.91, 7, '1971-6-2', 'Volante', true, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 248', 1.92, 8, '1982-6-27', 'Atacante', true, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 249', 1.96, 9, '1985-3-24', 'Goleiro', false, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 250', 1.93, 10, '1978-7-4', 'Goleiro', false, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 251', 1.69, 11, '1986-12-21', 'Zagueiro', false, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 252', 1.56, 12, '1962-12-5', 'Atacante', false, 21);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 253', 1.92, 1, '1971-3-28', 'Goleiro', true, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 254', 1.83, 2, '1987-5-9', 'Zagueiro', true, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 255', 1.92, 3, '1962-3-3', 'Lateral Esquerdo', true, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 256', 1.89, 4, '1969-3-3', 'Lateral Esquerdo', true, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 257', 1.61, 5, '1979-2-9', 'Lateral Direito', true, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 258', 1.89, 6, '1961-4-13', 'Lateral Direito', true, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 259', 1.78, 7, '1962-7-26', 'Volante', true, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 260', 1.92, 8, '1974-9-21', 'Atacante', true, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 261', 1.51, 9, '1961-10-27', 'Goleiro', false, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 262', 1.81, 10, '1971-8-10', 'Goleiro', false, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 263', 1.80, 11, '1982-2-24', 'Zagueiro', false, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 264', 1.76, 12, '1989-7-23', 'Atacante', false, 22);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 265', 1.73, 1, '1978-7-4', 'Goleiro', true, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 266', 1.58, 2, '1987-11-14', 'Zagueiro', true, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 267', 1.93, 3, '1968-3-25', 'Lateral Esquerdo', true, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 268', 1.56, 4, '1973-2-27', 'Lateral Esquerdo', true, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 269', 1.93, 5, '1976-7-3', 'Lateral Direito', true, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 270', 1.73, 6, '1971-11-6', 'Lateral Direito', true, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 271', 1.89, 7, '1968-8-17', 'Volante', true, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 272', 1.63, 8, '1977-8-15', 'Atacante', true, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 273', 1.83, 9, '1975-4-1', 'Goleiro', false, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 274', 1.60, 10, '1966-1-16', 'Goleiro', false, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 275', 1.64, 11, '1969-9-15', 'Zagueiro', false, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 276', 1.57, 12, '1989-5-2', 'Atacante', false, 23);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 277', 1.56, 1, '1961-1-22', 'Goleiro', true, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 278', 1.56, 2, '1980-3-27', 'Zagueiro', true, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 279', 1.81, 3, '1972-11-16', 'Lateral Esquerdo', true, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 280', 1.59, 4, '1984-10-28', 'Lateral Esquerdo', true, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 281', 1.97, 5, '1985-10-4', 'Lateral Direito', true, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 282', 1.85, 6, '1966-2-4', 'Lateral Direito', true, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 283', 1.76, 7, '1972-2-7', 'Volante', true, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 284', 1.68, 8, '1984-12-26', 'Atacante', true, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 285', 1.63, 9, '1983-3-24', 'Goleiro', false, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 286', 1.74, 10, '1983-2-13', 'Goleiro', false, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 287', 1.67, 11, '1974-10-17', 'Zagueiro', false, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 288', 1.63, 12, '1963-11-15', 'Atacante', false, 24);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 289', 1.74, 1, '1972-9-1', 'Goleiro', true, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 290', 1.92, 2, '1977-12-28', 'Zagueiro', true, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 291', 1.96, 3, '1963-5-21', 'Lateral Esquerdo', true, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 292', 1.65, 4, '1976-12-27', 'Lateral Esquerdo', true, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 293', 1.67, 5, '1976-1-4', 'Lateral Direito', true, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 294', 1.90, 6, '1966-12-10', 'Lateral Direito', true, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 295', 1.95, 7, '1988-6-25', 'Volante', true, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 296', 1.59, 8, '1989-6-3', 'Atacante', true, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 297', 1.72, 9, '1960-7-7', 'Goleiro', false, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 298', 1.71, 10, '1988-2-7', 'Goleiro', false, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 299', 1.96, 11, '1977-8-3', 'Zagueiro', false, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 300', 1.70, 12, '1968-8-14', 'Atacante', false, 25);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 301', 2.00, 1, '1974-11-5', 'Goleiro', true, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 302', 1.69, 2, '1961-7-12', 'Zagueiro', true, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 303', 1.54, 3, '1966-6-6', 'Lateral Esquerdo', true, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 304', 1.81, 4, '1962-4-27', 'Lateral Esquerdo', true, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 305', 1.65, 5, '1962-7-11', 'Lateral Direito', true, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 306', 1.56, 6, '1964-6-26', 'Lateral Direito', true, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 307', 1.90, 7, '1968-11-18', 'Volante', true, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 308', 1.51, 8, '1967-2-20', 'Atacante', true, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 309', 1.56, 9, '1980-2-19', 'Goleiro', false, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 310', 1.52, 10, '1984-6-13', 'Goleiro', false, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 311', 1.58, 11, '1960-8-7', 'Zagueiro', false, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 312', 1.64, 12, '1987-8-20', 'Atacante', false, 26);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 313', 1.57, 1, '1988-8-27', 'Goleiro', true, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 314', 1.68, 2, '1986-12-19', 'Zagueiro', true, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 315', 1.52, 3, '1988-4-7', 'Lateral Esquerdo', true, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 316', 1.74, 4, '1969-8-23', 'Lateral Esquerdo', true, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 317', 1.62, 5, '1966-5-25', 'Lateral Direito', true, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 318', 1.65, 6, '1970-9-19', 'Lateral Direito', true, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 319', 1.70, 7, '1981-9-10', 'Volante', true, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 320', 1.87, 8, '1966-8-8', 'Atacante', true, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 321', 1.57, 9, '1986-2-11', 'Goleiro', false, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 322', 1.70, 10, '1965-5-8', 'Goleiro', false, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 323', 1.82, 11, '1963-12-19', 'Zagueiro', false, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 324', 1.77, 12, '1973-3-3', 'Atacante', false, 27);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 325', 1.59, 1, '1983-11-23', 'Goleiro', true, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 326', 1.54, 2, '1974-7-25', 'Zagueiro', true, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 327', 1.78, 3, '1967-10-6', 'Lateral Esquerdo', true, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 328', 1.86, 4, '1966-6-17', 'Lateral Esquerdo', true, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 329', 1.79, 5, '1967-4-6', 'Lateral Direito', true, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 330', 1.74, 6, '1972-1-27', 'Lateral Direito', true, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 331', 1.63, 7, '1986-5-5', 'Volante', true, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 332', 1.88, 8, '1978-9-20', 'Atacante', true, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 333', 1.95, 9, '1961-5-5', 'Goleiro', false, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 334', 1.75, 10, '1967-5-23', 'Goleiro', false, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 335', 1.96, 11, '1985-12-11', 'Zagueiro', false, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 336', 1.99, 12, '1977-7-6', 'Atacante', false, 28);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 337', 1.86, 1, '1983-11-25', 'Goleiro', true, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 338', 1.90, 2, '1963-4-13', 'Zagueiro', true, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 339', 1.84, 3, '1974-12-12', 'Lateral Esquerdo', true, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 340', 1.97, 4, '1961-5-4', 'Lateral Esquerdo', true, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 341', 1.94, 5, '1970-7-11', 'Lateral Direito', true, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 342', 1.57, 6, '1962-8-18', 'Lateral Direito', true, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 343', 1.98, 7, '1967-10-11', 'Volante', true, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 344', 1.85, 8, '1966-11-5', 'Atacante', true, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 345', 1.77, 9, '1970-7-2', 'Goleiro', false, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 346', 1.64, 10, '1987-7-5', 'Goleiro', false, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 347', 1.55, 11, '1964-6-21', 'Zagueiro', false, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 348', 1.65, 12, '1967-6-18', 'Atacante', false, 29);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 349', 1.73, 1, '1977-11-8', 'Goleiro', true, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 350', 1.67, 2, '1975-5-8', 'Zagueiro', true, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 351', 1.61, 3, '1977-2-9', 'Lateral Esquerdo', true, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 352', 1.62, 4, '1986-8-6', 'Lateral Esquerdo', true, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 353', 1.97, 5, '1988-12-22', 'Lateral Direito', true, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 354', 1.77, 6, '1982-10-19', 'Lateral Direito', true, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 355', 1.97, 7, '1960-3-7', 'Volante', true, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 356', 1.63, 8, '1981-4-28', 'Atacante', true, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 357', 1.86, 9, '1989-9-1', 'Goleiro', false, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 358', 1.58, 10, '1971-4-26', 'Goleiro', false, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 359', 1.99, 11, '1978-4-6', 'Zagueiro', false, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 360', 1.65, 12, '1964-10-27', 'Atacante', false, 30);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 361', 1.98, 1, '1966-9-23', 'Goleiro', true, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 362', 1.72, 2, '1971-8-15', 'Zagueiro', true, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 363', 1.70, 3, '1975-2-26', 'Lateral Esquerdo', true, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 364', 1.68, 4, '1972-8-9', 'Lateral Esquerdo', true, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 365', 1.57, 5, '1978-11-7', 'Lateral Direito', true, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 366', 1.70, 6, '1979-3-16', 'Lateral Direito', true, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 367', 1.50, 7, '1981-9-16', 'Volante', true, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 368', 1.83, 8, '1978-8-19', 'Atacante', true, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 369', 1.69, 9, '1987-7-20', 'Goleiro', false, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 370', 1.96, 10, '1963-8-17', 'Goleiro', false, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 371', 1.88, 11, '1964-7-27', 'Zagueiro', false, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 372', 1.83, 12, '1968-11-11', 'Atacante', false, 31);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 373', 1.92, 1, '1985-12-17', 'Goleiro', true, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 374', 1.97, 2, '1962-3-26', 'Zagueiro', true, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 375', 1.59, 3, '1979-7-28', 'Lateral Esquerdo', true, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 376', 1.51, 4, '1972-8-1', 'Lateral Esquerdo', true, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 377', 1.59, 5, '1984-3-28', 'Lateral Direito', true, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 378', 1.96, 6, '1972-8-23', 'Lateral Direito', true, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 379', 1.62, 7, '1973-10-4', 'Volante', true, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 380', 1.96, 8, '1965-9-23', 'Atacante', true, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 381', 1.70, 9, '1965-5-17', 'Goleiro', false, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 382', 1.56, 10, '1984-8-5', 'Goleiro', false, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 383', 1.86, 11, '1982-1-12', 'Zagueiro', false, 32);
insert into Jogador (nome, altura, nCamisa, dataNasc, posicao, titular, idSelecao) values ('Jogador 384', 1.76, 12, '1978-2-17', 'Atacante', false, 32);