package sgcmf.model.hibernate;
// Generated 17/11/2012 16:51:03 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cartao generated by hbm2java
 */
public class Cartao  implements java.io.Serializable {


     private short id;
     private Ocorrencia ocorrencia;
     private Cartao cartao;
     private Jogador jogador;
     private String cor;
     private Set faltas = new HashSet(0);
     private Set cartaos = new HashSet(0);

    public Cartao() {
    }

	
    public Cartao(short id, Ocorrencia ocorrencia, Jogador jogador, String cor) {
        this.id = id;
        this.ocorrencia = ocorrencia;
        this.jogador = jogador;
        this.cor = cor;
    }
    public Cartao(short id, Ocorrencia ocorrencia, Cartao cartao, Jogador jogador, String cor, Set faltas, Set cartaos) {
       this.id = id;
       this.ocorrencia = ocorrencia;
       this.cartao = cartao;
       this.jogador = jogador;
       this.cor = cor;
       this.faltas = faltas;
       this.cartaos = cartaos;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public Ocorrencia getOcorrencia() {
        return this.ocorrencia;
    }
    
    public void setOcorrencia(Ocorrencia ocorrencia) {
        this.ocorrencia = ocorrencia;
    }
    public Cartao getCartao() {
        return this.cartao;
    }
    
    public void setCartao(Cartao cartao) {
        this.cartao = cartao;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public Set getFaltas() {
        return this.faltas;
    }
    
    public void setFaltas(Set faltas) {
        this.faltas = faltas;
    }
    public Set getCartaos() {
        return this.cartaos;
    }
    
    public void setCartaos(Set cartaos) {
        this.cartaos = cartaos;
    }




}


