package sgcmf.model.hibernate;
// Generated 24/11/2012 12:00:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jogo generated by hbm2java
 */
public class Jogo  implements java.io.Serializable {


     private short id;
     private Selecao selecaoByIdselecaoi;
     private Selecao selecaoByIdselecaoii;
     private String cidade;
     private String nomeestadio;
     private Date datahora;
     private Set ocorrencias = new HashSet(0);

    public Jogo() {
    }

	
    public Jogo(short id, String cidade, String nomeestadio, Date datahora) {
        this.id = id;
        this.cidade = cidade;
        this.nomeestadio = nomeestadio;
        this.datahora = datahora;
    }
    public Jogo(short id, Selecao selecaoByIdselecaoi, Selecao selecaoByIdselecaoii, String cidade, String nomeestadio, Date datahora, Set ocorrencias) {
       this.id = id;
       this.selecaoByIdselecaoi = selecaoByIdselecaoi;
       this.selecaoByIdselecaoii = selecaoByIdselecaoii;
       this.cidade = cidade;
       this.nomeestadio = nomeestadio;
       this.datahora = datahora;
       this.ocorrencias = ocorrencias;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public Selecao getSelecaoByIdselecaoi() {
        return this.selecaoByIdselecaoi;
    }
    
    public void setSelecaoByIdselecaoi(Selecao selecaoByIdselecaoi) {
        this.selecaoByIdselecaoi = selecaoByIdselecaoi;
    }
    public Selecao getSelecaoByIdselecaoii() {
        return this.selecaoByIdselecaoii;
    }
    
    public void setSelecaoByIdselecaoii(Selecao selecaoByIdselecaoii) {
        this.selecaoByIdselecaoii = selecaoByIdselecaoii;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getNomeestadio() {
        return this.nomeestadio;
    }
    
    public void setNomeestadio(String nomeestadio) {
        this.nomeestadio = nomeestadio;
    }
    public Date getDatahora() {
        return this.datahora;
    }
    
    public void setDatahora(Date datahora) {
        this.datahora = datahora;
    }
    public Set getOcorrencias() {
        return this.ocorrencias;
    }
    
    public void setOcorrencias(Set ocorrencias) {
        this.ocorrencias = ocorrencias;
    }




}


