package sgcmf.model.hibernate;
// Generated Oct 30, 2012 8:06:49 PM by Hibernate Tools 3.2.1.GA



/**
 * Rodadadepenaltis generated by hbm2java
 */
public class Rodadadepenaltis  implements java.io.Serializable {


     private short id;
     private Jogador jogadorByIdjogadorcobrancai;
     private Jogador jogadorByIdjogadorcobrancaii;
     private short idjogo;
     private short nrodada;
     private boolean resultadocobrancai;
     private boolean resultadocobrancaii;

    public Rodadadepenaltis() {
    }

    public Rodadadepenaltis(short id, Jogador jogadorByIdjogadorcobrancai, Jogador jogadorByIdjogadorcobrancaii, short idjogo, short nrodada, boolean resultadocobrancai, boolean resultadocobrancaii) {
       this.id = id;
       this.jogadorByIdjogadorcobrancai = jogadorByIdjogadorcobrancai;
       this.jogadorByIdjogadorcobrancaii = jogadorByIdjogadorcobrancaii;
       this.idjogo = idjogo;
       this.nrodada = nrodada;
       this.resultadocobrancai = resultadocobrancai;
       this.resultadocobrancaii = resultadocobrancaii;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public Jogador getJogadorByIdjogadorcobrancai() {
        return this.jogadorByIdjogadorcobrancai;
    }
    
    public void setJogadorByIdjogadorcobrancai(Jogador jogadorByIdjogadorcobrancai) {
        this.jogadorByIdjogadorcobrancai = jogadorByIdjogadorcobrancai;
    }
    public Jogador getJogadorByIdjogadorcobrancaii() {
        return this.jogadorByIdjogadorcobrancaii;
    }
    
    public void setJogadorByIdjogadorcobrancaii(Jogador jogadorByIdjogadorcobrancaii) {
        this.jogadorByIdjogadorcobrancaii = jogadorByIdjogadorcobrancaii;
    }
    public short getIdjogo() {
        return this.idjogo;
    }
    
    public void setIdjogo(short idjogo) {
        this.idjogo = idjogo;
    }
    public short getNrodada() {
        return this.nrodada;
    }
    
    public void setNrodada(short nrodada) {
        this.nrodada = nrodada;
    }
    public boolean isResultadocobrancai() {
        return this.resultadocobrancai;
    }
    
    public void setResultadocobrancai(boolean resultadocobrancai) {
        this.resultadocobrancai = resultadocobrancai;
    }
    public boolean isResultadocobrancaii() {
        return this.resultadocobrancaii;
    }
    
    public void setResultadocobrancaii(boolean resultadocobrancaii) {
        this.resultadocobrancaii = resultadocobrancaii;
    }




}


