package sgcmf.model;
// Generated Oct 27, 2012 11:54:54 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cartao generated by hbm2java
 */
public class Cartao  implements java.io.Serializable {


     private short idoc;
     private Ocorrencia ocorrencia;
     private Jogador jogador;
     private String cor;
     private Set faltas = new HashSet(0);

    public Cartao() {
    }

	
    public Cartao(short idoc, Ocorrencia ocorrencia, Jogador jogador, String cor) {
        this.idoc = idoc;
        this.ocorrencia = ocorrencia;
        this.jogador = jogador;
        this.cor = cor;
    }
    public Cartao(short idoc, Ocorrencia ocorrencia, Jogador jogador, String cor, Set faltas) {
       this.idoc = idoc;
       this.ocorrencia = ocorrencia;
       this.jogador = jogador;
       this.cor = cor;
       this.faltas = faltas;
    }
   
    public short getIdoc() {
        return this.idoc;
    }
    
    public void setIdoc(short idoc) {
        this.idoc = idoc;
    }
    public Ocorrencia getOcorrencia() {
        return this.ocorrencia;
    }
    
    public void setOcorrencia(Ocorrencia ocorrencia) {
        this.ocorrencia = ocorrencia;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public Set getFaltas() {
        return this.faltas;
    }
    
    public void setFaltas(Set faltas) {
        this.faltas = faltas;
    }




}


