package sgcmf.model;
// Generated Oct 26, 2012 6:12:10 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * Gol generated by hbm2java
 */
public class Gol  implements java.io.Serializable {


     private short idoc;
     private Ocorrencia ocorrencia;
     private Jogador jogador;
     private short idjogadorautor;
     private Serializable tipo;
     private Serializable modo;

    public Gol() {
    }

	
    public Gol(short idoc, Ocorrencia ocorrencia, short idjogadorautor, Serializable tipo, Serializable modo) {
        this.idoc = idoc;
        this.ocorrencia = ocorrencia;
        this.idjogadorautor = idjogadorautor;
        this.tipo = tipo;
        this.modo = modo;
    }
    public Gol(short idoc, Ocorrencia ocorrencia, Jogador jogador, short idjogadorautor, Serializable tipo, Serializable modo) {
       this.idoc = idoc;
       this.ocorrencia = ocorrencia;
       this.jogador = jogador;
       this.idjogadorautor = idjogadorautor;
       this.tipo = tipo;
       this.modo = modo;
    }
   
    public short getIdoc() {
        return this.idoc;
    }
    
    public void setIdoc(short idoc) {
        this.idoc = idoc;
    }
    public Ocorrencia getOcorrencia() {
        return this.ocorrencia;
    }
    
    public void setOcorrencia(Ocorrencia ocorrencia) {
        this.ocorrencia = ocorrencia;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public short getIdjogadorautor() {
        return this.idjogadorautor;
    }
    
    public void setIdjogadorautor(short idjogadorautor) {
        this.idjogadorautor = idjogadorautor;
    }
    public Serializable getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Serializable tipo) {
        this.tipo = tipo;
    }
    public Serializable getModo() {
        return this.modo;
    }
    
    public void setModo(Serializable modo) {
        this.modo = modo;
    }




}


