package sgcmf.model;
// Generated Oct 27, 2012 11:54:54 AM by Hibernate Tools 3.2.1.GA



/**
 * Gol generated by hbm2java
 */
public class Gol  implements java.io.Serializable {


     private short idoc;
     private Ocorrencia ocorrencia;
     private Jogador jogador;
     private short idjogadorautor;
     private String tipo;
     private String modo;

    public Gol() {
    }

	
    public Gol(short idoc, Ocorrencia ocorrencia, short idjogadorautor, String tipo, String modo) {
        this.idoc = idoc;
        this.ocorrencia = ocorrencia;
        this.idjogadorautor = idjogadorautor;
        this.tipo = tipo;
        this.modo = modo;
    }
    public Gol(short idoc, Ocorrencia ocorrencia, Jogador jogador, short idjogadorautor, String tipo, String modo) {
       this.idoc = idoc;
       this.ocorrencia = ocorrencia;
       this.jogador = jogador;
       this.idjogadorautor = idjogadorautor;
       this.tipo = tipo;
       this.modo = modo;
    }
   
    public short getIdoc() {
        return this.idoc;
    }
    
    public void setIdoc(short idoc) {
        this.idoc = idoc;
    }
    public Ocorrencia getOcorrencia() {
        return this.ocorrencia;
    }
    
    public void setOcorrencia(Ocorrencia ocorrencia) {
        this.ocorrencia = ocorrencia;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public short getIdjogadorautor() {
        return this.idjogadorautor;
    }
    
    public void setIdjogadorautor(short idjogadorautor) {
        this.idjogadorautor = idjogadorautor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getModo() {
        return this.modo;
    }
    
    public void setModo(String modo) {
        this.modo = modo;
    }




}


